#include "codegen_header.h"

/* Auto-generated by codegen_mappings.py tables */

static const uint8_t hid_keyboard_descriptor[] = {
	0x05,0x01,      /* Usage Page (Generic Desktop) */
	0x09,0x06,      /* Usage (Keyboard) */
	0xa1,0x01,      /* Collection (Application) */
	0x75,0x01,      /* Report Size (1) */
	0x95,0x08,      /* Report Count (8) */
	0x05,0x07,      /* Usage Page (Keyboard) */
	0x19,0xe0,      /* Usage Minimum (224) */
	0x29,0xe7,      /* Usage Maximum (231) */
	0x15,0x00,      /* Logical Minimum (0) */
	0x25,0x01,      /* Logical Maximum (1) */
	0x81,0x02,      /* Input (Data, Variable, Absolute) */
	0x95,0x01,      /* Report Count (1) */
	0x75,0x08,      /* Report Size (8) */
	0x81,0x01,      /* Input (Constant) */
	0x95,0x05,      /* Report Count (5) */
	0x75,0x01,      /* Report Size (1) */
	0x05,0x08,      /* Usage Page (LED) */
	0x19,0x01,      /* Usage Minimum (1) */
	0x29,0x05,      /* Usage Maximum (5) */
	0x91,0x02,      /* Output (Data, Variable, Absolute) */
	0x95,0x01,      /* Report Count (1) */
	0x75,0x03,      /* Report Size (3) */
	0x91,0x01,      /* Output (Constant) */
	0x95,0x06,      /* Report Count (6) */
	0x75,0x08,      /* Report Size (8) */
	0x81,0x01,      /* Input (Constant) */
	0x05,0x07,      /* Usage Page (Keyboard) */
	0x75,0x01,      /* Report Size (1) */
	0x95,0x4f,      /* Report Count (79) */
	0x19,0x04,      /* Usage Minimum (4) */
	0x29,0x52,      /* Usage Maximum (82) */
	0x81,0x02,      /* Input (Data, Variable, Absolute) */
	0x75,0x01,      /* Report Size (1) */
	0x95,0x01,      /* Report Count (1) */
	0x81,0x01,      /* Input (Constant) */
	0xc0,           /* End Collection */

};

static const uint32_t matrix_to_keycode[] = {
	[MATRIX_esc]          = KEYCODE_esc,
	[MATRIX_f1]           = KEYCODE_f1,
	[MATRIX_f2]           = KEYCODE_f2,
	[MATRIX_f3]           = KEYCODE_f3,
	[MATRIX_f4]           = KEYCODE_f4,
	[MATRIX_f5]           = KEYCODE_f5,
	[MATRIX_f6]           = KEYCODE_f6,
	[MATRIX_f7]           = KEYCODE_f7,
	[MATRIX_f8]           = KEYCODE_f8,
	[MATRIX_f9]           = KEYCODE_f9,
	[MATRIX_f10]          = KEYCODE_f10,
	[MATRIX_f11]          = KEYCODE_f11,
	[MATRIX_f12]          = KEYCODE_f12,
	[MATRIX_printscreen]  = KEYCODE_printscreen,
	[MATRIX_scrollock]    = KEYCODE_scrollock,
	[MATRIX_pause]        = KEYCODE_pause,
	[MATRIX_tilde]        = KEYCODE_tilde,
	[MATRIX_1]            = KEYCODE_1,
	[MATRIX_2]            = KEYCODE_2,
	[MATRIX_3]            = KEYCODE_3,
	[MATRIX_4]            = KEYCODE_4,
	[MATRIX_5]            = KEYCODE_5,
	[MATRIX_6]            = KEYCODE_6,
	[MATRIX_7]            = KEYCODE_7,
	[MATRIX_8]            = KEYCODE_8,
	[MATRIX_9]            = KEYCODE_9,
	[MATRIX_0]            = KEYCODE_0,
	[MATRIX_minus]        = KEYCODE_minus,
	[MATRIX_equals]       = KEYCODE_equals,
	[MATRIX_backspace]    = KEYCODE_backspace,
	[MATRIX_insert]       = KEYCODE_insert,
	[MATRIX_home]         = KEYCODE_home,
	[MATRIX_tab]          = KEYCODE_tab,
	[MATRIX_q]            = KEYCODE_q,
	[MATRIX_w]            = KEYCODE_w,
	[MATRIX_e]            = KEYCODE_e,
	[MATRIX_r]            = KEYCODE_r,
	[MATRIX_t]            = KEYCODE_t,
	[MATRIX_y]            = KEYCODE_y,
	[MATRIX_u]            = KEYCODE_u,
	[MATRIX_i]            = KEYCODE_i,
	[MATRIX_o]            = KEYCODE_o,
	[MATRIX_p]            = KEYCODE_p,
	[MATRIX_openbracket]  = KEYCODE_openbracket,
	[MATRIX_closebracket] = KEYCODE_closebracket,
	[MATRIX_backslash]    = KEYCODE_backslash,
	[MATRIX_delete]       = KEYCODE_delete,
	[MATRIX_end]          = KEYCODE_end,
	[MATRIX_capslock]     = KEYCODE_capslock,
	[MATRIX_a]            = KEYCODE_a,
	[MATRIX_s]            = KEYCODE_s,
	[MATRIX_d]            = KEYCODE_d,
	[MATRIX_f]            = KEYCODE_f,
	[MATRIX_g]            = KEYCODE_g,
	[MATRIX_h]            = KEYCODE_h,
	[MATRIX_j]            = KEYCODE_j,
	[MATRIX_k]            = KEYCODE_k,
	[MATRIX_l]            = KEYCODE_l,
	[MATRIX_semicolon]    = KEYCODE_semicolon,
	[MATRIX_quote]        = KEYCODE_quote,
	[MATRIX_enter]        = KEYCODE_enter,
	[0x3d]                = KEY_NONE,
	[0x3e]                = KEY_NONE,
	[MATRIX_pageup]       = KEYCODE_pageup,
	[MATRIX_leftshift]    = KEYCODE_leftshift,
	[MATRIX_z]            = KEYCODE_z,
	[MATRIX_x]            = KEYCODE_x,
	[MATRIX_c]            = KEYCODE_c,
	[MATRIX_v]            = KEYCODE_v,
	[MATRIX_b]            = KEYCODE_b,
	[MATRIX_n]            = KEYCODE_n,
	[MATRIX_m]            = KEYCODE_m,
	[MATRIX_comma]        = KEYCODE_comma,
	[MATRIX_dot]          = KEYCODE_dot,
	[MATRIX_slash]        = KEYCODE_slash,
	[0x4b]                = KEY_NONE,
	[MATRIX_rightshift]   = KEYCODE_rightshift,
	[0x4d]                = KEY_NONE,
	[MATRIX_up]           = KEYCODE_up,
	[MATRIX_pagedown]     = KEYCODE_pagedown,
	[MATRIX_leftcontrol]  = KEYCODE_leftcontrol,
	[MATRIX_fn]           = KEY_NONE,
	[MATRIX_alt]          = KEYCODE_alt,
	[0x53]                = KEY_NONE,
	[0x54]                = KEY_NONE,
	[MATRIX_space]        = KEYCODE_space,
	[0x56]                = KEY_NONE,
	[0x57]                = KEY_NONE,
	[MATRIX_altgr]        = KEYCODE_altgr,
	[MATRIX_win]          = KEYCODE_win,
	[0x5a]                = KEY_NONE,
	[MATRIX_menu]         = KEYCODE_menu,
	[MATRIX_rightcontrol] = KEYCODE_rightcontrol,
	[MATRIX_left]         = KEYCODE_left,
	[MATRIX_down]         = KEYCODE_down,
	[MATRIX_right]        = KEYCODE_right,
};

static const uint8_t matrix_to_led[] = {
	[MATRIX_esc]          = LED_esc,
	[MATRIX_f1]           = LED_f1,
	[MATRIX_f2]           = LED_f2,
	[MATRIX_f3]           = LED_f3,
	[MATRIX_f4]           = LED_f4,
	[MATRIX_f5]           = LED_f5,
	[MATRIX_f6]           = LED_f6,
	[MATRIX_f7]           = LED_f7,
	[MATRIX_f8]           = LED_f8,
	[MATRIX_f9]           = LED_f9,
	[MATRIX_f10]          = LED_f10,
	[MATRIX_f11]          = LED_f11,
	[MATRIX_f12]          = LED_f12,
	[MATRIX_printscreen]  = LED_printscreen,
	[MATRIX_scrollock]    = LED_scrollock,
	[MATRIX_pause]        = LED_pause,
	[MATRIX_tilde]        = LED_tilde,
	[MATRIX_1]            = LED_1,
	[MATRIX_2]            = LED_2,
	[MATRIX_3]            = LED_3,
	[MATRIX_4]            = LED_4,
	[MATRIX_5]            = LED_5,
	[MATRIX_6]            = LED_6,
	[MATRIX_7]            = LED_7,
	[MATRIX_8]            = LED_8,
	[MATRIX_9]            = LED_9,
	[MATRIX_0]            = LED_0,
	[MATRIX_minus]        = LED_minus,
	[MATRIX_equals]       = LED_equals,
	[MATRIX_backspace]    = LED_backspace,
	[MATRIX_insert]       = LED_insert,
	[MATRIX_home]         = LED_home,
	[MATRIX_tab]          = LED_tab,
	[MATRIX_q]            = LED_q,
	[MATRIX_w]            = LED_w,
	[MATRIX_e]            = LED_e,
	[MATRIX_r]            = LED_r,
	[MATRIX_t]            = LED_t,
	[MATRIX_y]            = LED_y,
	[MATRIX_u]            = LED_u,
	[MATRIX_i]            = LED_i,
	[MATRIX_o]            = LED_o,
	[MATRIX_p]            = LED_p,
	[MATRIX_openbracket]  = LED_openbracket,
	[MATRIX_closebracket] = LED_closebracket,
	[MATRIX_backslash]    = LED_backslash,
	[MATRIX_delete]       = LED_delete,
	[MATRIX_end]          = LED_end,
	[MATRIX_capslock]     = LED_capslock,
	[MATRIX_a]            = LED_a,
	[MATRIX_s]            = LED_s,
	[MATRIX_d]            = LED_d,
	[MATRIX_f]            = LED_f,
	[MATRIX_g]            = LED_g,
	[MATRIX_h]            = LED_h,
	[MATRIX_j]            = LED_j,
	[MATRIX_k]            = LED_k,
	[MATRIX_l]            = LED_l,
	[MATRIX_semicolon]    = LED_semicolon,
	[MATRIX_quote]        = LED_quote,
	[MATRIX_enter]        = LED_enter,
	[0x3d]                = LED_unused,
	[0x3e]                = LED_unused,
	[MATRIX_pageup]       = LED_pageup,
	[MATRIX_leftshift]    = LED_leftshift,
	[MATRIX_z]            = LED_z,
	[MATRIX_x]            = LED_x,
	[MATRIX_c]            = LED_c,
	[MATRIX_v]            = LED_v,
	[MATRIX_b]            = LED_b,
	[MATRIX_n]            = LED_n,
	[MATRIX_m]            = LED_m,
	[MATRIX_comma]        = LED_comma,
	[MATRIX_dot]          = LED_dot,
	[MATRIX_slash]        = LED_slash,
	[0x4b]                = LED_unused,
	[MATRIX_rightshift]   = LED_rightshift,
	[0x4d]                = LED_unused,
	[MATRIX_up]           = LED_up,
	[MATRIX_pagedown]     = LED_pagedown,
	[MATRIX_leftcontrol]  = LED_leftcontrol,
	[MATRIX_fn]           = LED_fn,
	[MATRIX_alt]          = LED_alt,
	[0x53]                = LED_unused,
	[0x54]                = LED_unused,
	[MATRIX_space]        = LED_space,
	[0x56]                = LED_unused,
	[0x57]                = LED_unused,
	[MATRIX_altgr]        = LED_altgr,
	[MATRIX_win]          = LED_win,
	[0x5a]                = LED_unused,
	[MATRIX_menu]         = LED_menu,
	[MATRIX_rightcontrol] = LED_rightcontrol,
	[MATRIX_left]         = LED_left,
	[MATRIX_down]         = LED_down,
	[MATRIX_right]        = LED_right,
};

